RFM69.cpp

RFM69::readTemperature was emitting * characters on Serial while waiting for a reading, which was interfering with communications on the serial port.

RFM69::readTemperature no longer emits * characters on Serial

---

Examples/OLEDMote/OLEDMote.ino
Examples/Struct_receive/Struct_receive.ino
Examples/Struct_send/Struct_send.ino
RFM69.cpp
RFM69.h
RFM69registers.h

Use `git diff --ignore-space-change` to verify.
The code should now look the same in many kinds of editors.

Unify indentation (from TAB to two spaces)

---

RFM69.cpp
RFM69registers.h

Reviewed datasheet [RFM69CW-V1.1 p. 60ff](http://www.hoperf.com/upload/rf/RFM69CW-V1.1.pdf#page=60).
`Configuration and Status Registers` states that some reset values differ from recommended default values! Disabled 1MHz ClkOut on DIO5 to save power as recommended.
`RegLna(0x18)` and `RegAfcBw(0x1A)` may be further investigated.

Update RFM69registers.h for reset / recommended default vals., ClkOut

---

RFM69.cpp

by https://github.com/vmire/Arduino_lib_RFM69/commit/fca63f659dd5eb775b30fb1cf8b9f0fd44b56bd5

Save program space by calculating CTLbyte instead of fixed literal

---

Examples/Node/Node.ino

Without this, trying to compile with PlatformIO yields (on OSX El Capitan but I'm seeing the same error trying to compile on an Pi2). I checked and this also affects other examples:
```
✔ ~/moteino
02:27 $ platformio run
[Mon Mar  7 02:27:50 2016] Processing moteino (platform: atmelavr, board: moteino, framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Installing toolchain-atmelavr package:
Already installed
Installing tool-scons package:
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Installing framework-arduinoavr package:
Downloading  [####################################] …
```

Moving Blink def so it compiles on PlatformIO

---

RFM69.cpp
RFM69.h

The unselect() method, liberally called directly and indirectly
from the interrupt handler, always reenables interrupts after it's
done. In ISRs, interrupts are disabled by default, and although
reenabling is allowed, the interrupt handler doesn't seem to have
reentrant code. Therefore, only reenable when not in an ISR.
This was causing problems in certain circumstances, e.g. with
an Arduino Ethernet shield, most packet receptions would cause
resets.

Don't reenable interrupts in the ISR

---

RFM69.cpp

This interrupt is then masked during SPI transactions of other
code/libraries that use SPI transactions, to prevent the RFM69
interrupt handler (which does SPI transfers) preempting other SPI
transfers.

Declare RFM69 interrupt with SPI.usingInterrupt()

---

RFM69.cpp

Reverts LowPowerLab/RFM69#46
Causing freezes on 1.6.9 (although none on 1.0.6).

Revert "Declare RFM69 interrupt with SPI.usingInterrupt()"

---

RFM69.cpp
RFM69.h
RFM69_OTA.cpp
RFM69_OTA.h

This allows the caller to specify a specific SPIClass when constructing RFM69. This is useful on ARM boards that have multiple SPI interfaces. Defaults to SPI, so it preserves existing behavior.
Also disables RFM69_OTA if the arch isn't AVR, since it depends on the AVR watchdog #56 .

Allow choosing the SPI interface

---

RFM69.cpp
RFM69_ATC.cpp
RFM69_ATC.h
RFM69_OTA.cpp
RFM69_OTA.h

Hey,
I've been doing some refactoring and discovered strange include problem with having rfm69.h file in my project directory. Using platformio on Windows, it does not distinguish RFM69.h and rfm69.h b/c of case insensitive filesystem.
I am not yet sure why exactly platformio uses global include path like that, but in any case I think it would be a useful change here to have relative include instead of absolute to signify that we are using local headers and not some external ones.

Use relative includes

---

RFM69.cpp
RFM69.h
RFM69_ATC.cpp
RFM69_ATC.h

There is an old [open issue](https://github.com/LowPowerLab/RFM69/pull/100) about adding SPI support, that I didn't open. This new one seems to be working.
I added a few changes so we can pass a predefined SPIClass into the constructor.
For example with a MKR1000 (SAMD) board, we can define a new SPI bus on pins 0,1 and 6:
`SPIClass mySPI (&sercom3, 6, 1, 0, SPI_PAD_0_SCK_1, SERCOM_RX_PAD_2); //MISO(6), SCK(1), MOSI(0)`
And later we can call the constructor with additional parameters if we want:
`#ifdef ENABLE_ATC`
`RFM69_ATC radio(RFM69_CS, A2, is_rfm69hw_hcw, &mySPI);`
`#else`
`RFM69 radio(RFM69_CS, A2, is_rfm69hw_hcw, &mySPI);`
`#endif`
I can confirm it is working as of 02 June 2020 with MKR1000 and not interfering with standard Moteino (-USB), and very likely with any other one …

Custom SPI support

---

RFM69.h

This little change makes is possible for ESP8266 users to add a layer on top your lib that injects a delay(1) to canSend() . This would help to solve for example #105 and #49

set canSend to virtual

---

RFM69.cpp

When enabling RF69_LISTENMODE_ENABLE we get compile error. Just a small typo.

Fix typo in listenModeInterruptHandler method.

---

RFM69.h

Noticed here:
https://github.com/xoseperez/espurna/runs/1757526551?check_suite_focus=true#step:9:290
Avoids `RFM69.h:141:0: warning: "RF69_SPI_CS" redefined [enabled by default]'
Remove esp8266 & esp32 flags, always infer the value through SS
Move definition down to stand out a bit more
My understanding is that we always have `SS` through the Arduino.h 'variant' constants
(but I guess originally this was not the case?)

Do not redefine RF69_SPI_CS

---

RFM69.cpp
RFM69.h
RFM69_OTA.cpp

Some information: 
* In the Arduino library, the interrupt number is a uint8_t, but NOT_AN_INTERRUPT is defined as -1! So this isn't logic, and as the function digitalPinToInterrupt can return -1, the variable should be a signed integer
* Added some "unused" attributes to tell the compiler to not car about the unused variables
* The formatting of uint16_t is %u and not %hu (https://en.wikipedia.org/wiki/C_data_types) as uint16_t = unsigned int

fixing some warnings

---

RFM69.cpp

Since initialize() erases the encryption key, we need to store that we have it (or not) before calling initialize(), and then use that stored value

Fixing a bug with restoring encryption in listen mode

---

RFM69.cpp

Have several students working with the RFM69 lib and facing problems with the ACKs as described in #105 and #49.
Deriving a new function as suggested in #150 results a lot of overhead work for me. So I hope that the suggested PR adding the required `delay(0);` for the esp8266 platform will be accepted.

Fix for esp8266 ACK problem. Solution as suggested in #49 and #105

---

RFM69.cpp
RFM69.h

This library works well on ESP32, and I've been using it for a couple of years to re-send data from low-power nodes to an MQTT broker. The only downside for me is that partially it relays on polling instead of being fully interrupt-driven.
I've seen a few discussions about adding an ISR callback, but it was never done. So here it is.
A few additional notes:
- ISR method should have IRAM_ATTR
`void IRAM_ATTR isrRadioMessage();`
- ISR should not block (it must be simple and fast)
- `radio.receiveDone()` should be called after the radio initialization
An example that demonstrates the usage:
```cpp
SPIClass spi;
RFM69 radio(RFM_CS, RFM_INT, RFM_HW, &spi);
EventGroupHandle_t eg;
SemaphoreHandle_t semaRadio;
#define EVENT_RADIO_MESSAGE (1 << 0)
void IRAM_ATTR isrRadioMessage()
{
BaseType_t …
```

ISR callback in a user space

---

RFM69.cpp

spi->begin() chooses VSPI pin numbering by default.

Revert redundant pin numbering for ESP32

---

Examples/TestSetup/TestSetup.ino
README.md
RFM69.cpp
RFM69.h
RFM69_ATC.cpp
RFM69_ATC.h

- `getVersion()` to read RFM version
- `getAddress()` to return configured node ID
- `getNetwork()` to return configured network ID
- `getFrequencyDeviation()` to read frequency deviation
- `getBitRate()` to read the modulation bitrate in bits/second
- `getSpyMode()` to return spy mode setting
- `isSyncOn()`
- `getSyncSize()`
- `isCrcOn()` to check if CRC is activated
- `isAesOn()` to check if encryption is enabled
- `isHighPower()` to check if module is configured as HCW or not
- `dBm_to_mW()` to convert dBm to mW
- `getOutputPower()` to get the configured output power instead of returning the last
- `getTargetRssi()` to get the configured RSSI value, only for RFM69_ATC
- `_networkID` made public to get it via `getNetwork()` function
Plus the demo sketch …

Add new getter functions to RFM69 and RFM69 ATC
